name: Trigger Netlify Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        if: ${{ secrets.NETLIFY_BUILD_HOOK_URL != '' }}
        run: |
          curl -X POST -d '{}' "$NETLIFY_BUILD_HOOK_URL"
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}

      - name: Missing secret notice
        if: ${{ secrets.NETLIFY_BUILD_HOOK_URL == '' }}
        run: |
          echo "NETLIFY_BUILD_HOOK_URL secret is not set."
          echo "Create a Netlify Build Hook for your site, then add the URL as a repository secret named NETLIFY_BUILD_HOOK_URL."
